### PR TITLE
added new neurofuzzy classifier

### PR DESCRIPTION
**Pull request by fbenites**

### CODE REVIEW

**Comment by niedakh** [comment]
I'll release 0.0.2 ASAP and I'll take a moment to review this for 0.0.3, thank you for the PR!

**Comment by niedakh** [comment]
Hi @fbenites,

I've looked at your code, and I'd like to ask you if could correct a couple of elements:
- could you make predict use proba internally? the functions do not differ apart from additional few steps in predict:

```diff
--- proba	2016-06-15 16:01:04.066880611 +0200
+++ predict	2016-06-15 16:01:17.846820196 +0200
@@ -87,6 +87,21 @@
                 actives.append(sortedact[i])
                 activity_actives.append(activity[sortedact[i]])
             rank /= rbsum
+
+            sortedRankarg = numpy.argsort(-rank)
+            diffs = -numpy.diff([rank[k] for k in sortedRankarg])
+
+            indcutt = numpy.where(diffs == (diffs).max())[0]
+            if len(indcutt.shape) == 1:
+                indcut = indcutt[0] + 1
+            else:
+                indcut = indcutt[0, -1] + 1
+            label = numpy.zeros(rank.shape)
+
+            label[sortedRankarg[0:indcut]] = 1
+
+            result.append(label)
             allranks.append(rank)
+            neuronsactivated.append((actives, activity_actives))
 
-        return numpy.array(numpy.matrix(allranks))
\ No newline at end of file
+        return numpy.array(numpy.matrix(result))
\ No newline at end of file
```

- could you clean up the code a little - remove some of the commented code blocks with prints etc?
- maybe a few more numpydocs documentation to the constructor, similar to the docs in MLClassifierBase? just to let people know which parameters are what?
- ideally if you could add a tests subdirectory and make small file test_neurofuzzy.py that tests how the classifier works, you can use examples from other tests I've written on master

Thank you again for your work, please tell me whether my remarks make sense to you :)

**Comment by fbenites** [comment]
Hi Piotr,

About proba, the question is if i should call proba for each sample or 
for the whole batch.
I mean, if I go straight forward with your suggestion, I will need to 
iterate over all the samples again, turning rankings into predictions
for every sample. This would be not so efficient.
This is a design question, since you are the  maintainer you should 
decide, I can easily implement as above mentioned, or implement a sample 
wise proba, or something else. I would only like to know which you find 
best, and please consider that my algorithm was done for large datasets.

I am doing the other stuff also. I did a MLARAMfastTesting.ipynb for 
testing but did not upload, would you like that also?
I will do the test file also this week.

Cheers and thank you also for your work,
Fernando

Am 15.06.2016 um 16:06 schrieb Piotr Szymański:

**Comment by niedakh** [comment]
Maybe use just proba then, and add a parameter to proba: predict=False by default and a return self.proba(X, predict=True) ?

This is of course not entirely beautiful, but makes us reuse code and saves us from unforeseen mistakes when we fix a bug in proba and not predict or vice versa because of overlooking.  Do you think this is a good idea?

**Comment by fbenites** [comment]
I was thinking now about big O now, and not if xrange should rerun once more, and it makes sense to put all proba in predict and apply the ML-filtering afterwards.
The decrease should be negligible  and even enforce the online /sample-wise method of the classifier.
I will change accordingly and upload this weekend.

**Comment by fbenites** [comment]
Could you check this new commit please? I will add a notebook script later

**Comment by niedakh** [comment]
Thank you, I'll check it in the morning :)

**Comment by niedakh** [comment]
I've merged your code in, I will do minor corrections:
- you are using mlclassifierbase - correctly as you are not transforming the problem to a single-label classification case - but as you are not transforming, you do not have a base classifier thus no need to use require_dense or classifier fields and mlclassifierbase constructor does not even take them. I will fix them in a moment.
- I will run autopep8 on it - you might want to try it, its a lovely tool to make coded PEP8 compliant without having to remember the PEP8 stuff

**Comment by fbenites** [comment]
Hi,

sure, I know about autopep8 (did some stuff for scikit, they requested that too) but I did forgot about that.
The dense thing is complicated, I have also implementations handling sparse inputs, and optimized for that but it requires cython...
How is your opinion about adding a part in cython?

Cheers,
Fernando

**Comment by niedakh** [comment]
@fbenites  I'm ok with the cpython part if you have it :)

btw. scikit-multilearn is BSD-licenced, so I understand that's ok with you for your submission to be licenced so as you have submitted the code for inclusion?

**Pull request merged**
