### PR TITLE
#152: fixes error that causes appveyor to fail

### PR DESCRIPTION
**Pull request by ChristianSch**
see  #152

### CODE REVIEW

**Comment by ChristianSch** [comment]
Now fails with:

adding 'PURELIB\skmultilearn\problem_transform\__init__.py'
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    u'Topic :: Scientific/Engineering :: Bio-Informatics',
  File "C:\Python36\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Python36\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python36\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python36\lib\site-packages\setuptools\command\bdist_wininst.py", line 19, in run
    orig.bdist_wininst.run(self)
  File "C:\Python36\lib\distutils\command\bdist_wininst.py", line 179, in run
    self.create_exe(arcname, fullname, self.bitmap)
  File "C:\Python36\lib\distutils\command\bdist_wininst.py", line 262, in create_exe
    cfgdata = cfgdata.encode("mbcs")
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

**Comment by aamin21** [comment]
@ChristianSch Was this fixed? I am about to make a PR but it seems the build will fail. Is this project not being maintained?

**Comment by ChristianSch** [comment]
Not sure, but I don’t think I ever got around to fix it. I might have some code lying around on my old laptop on this.

I actually moved on and have no need for the library anymore, so I don’t think I’ll do any work on this in the future, don’t know about the rest though.

**Comment by azmainamin** [comment]
> 
> Not sure, but I don’t think I ever got around to fix it. I might have some code lying around on my old laptop on this. I actually moved on and have no need for the library anymore, so I don’t think I’ll do any work on this in the future, don’t know about the rest though.
> […](#)
> Sent from my iPhone
> On 24. Jan 2020, at 20:45, Azmain Amin ***@***.***> wrote: ﻿ @ChristianSch Was this fixed? I am about to make a PR but it seems the build will fail. Is this project not being maintained? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply! I made a PR to fix this. Is this library not being maintained anymore?

**Comment by ChristianSch** [comment]
The lib always had problems with maintenance, as niedakh is mostly on his own. I helped out a bit with a few others, but they and I as well have moved on I guess.

**Pull request closed without merging**
