### PR TITLE
get_params and set_params fixed / cross validation test case added

### PR DESCRIPTION
**Pull request by ChristianSch**
I can't really test the cross validation itself, though cloning (sklearn.base.clone) works. Python gets a SIGKILL from somewhere. Maybe something on my side is wrong, should work though. Other than in the other pull request the deep copying of classifier (i.e.) works. (`hasattr(getattr(self, attr), 'get_params')` is the correct one)

See #29 for reference.

### CODE REVIEW

**Comment by ChristianSch** [comment]
FYI: this is the output of the params:
```
>>> c2.get_params(deep=True)
{'classifier__bootstrap': True, 'classifier__max_features': 'auto', 'classifier__max_depth': None, 'classifier__min_samples_split': 2, 'classifier__min_weight_fraction_leaf': 0.0, 'classifier__oob_score': False, 'classifier__class_weight': None, 'classifier__n_estimators': 66, 'classifier__max_leaf_nodes': None, 'classifier__random_state': None, 'classifier__min_samples_leaf': 1, 'classifier__warm_start': False, 'require_dense': [True, True], 'classifier__n_jobs': 1, 'classifier': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=66, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False), 'classifier__verbose': 0, 'classifier__criterion': 'gini'}
```

for the classifier:
```
c2 = BinaryRelevance(RandomForestClassifier(n_estimators=66))
```

**Comment by ChristianSch** [comment]
Needs further testing.

**Comment by ChristianSch** [comment]
```
c2.set_params(**c1.get_params())
```
```
c2.set_params(**c1.get_params(deep=True))
```
```
c2 = clone(c1)
```

Do all work now.
Context:
```
from skmultilearn.meta import br
from sklearn.ensemble import RandomForestClassifier
from sklearn.base import clone

c1 = br.BinaryRelevance(RandomForestClassifier(n_estimators=66))

**Comment by ChristianSch** [comment]
@niedakh From my point of view this can be merged now.

**Comment by niedakh** [comment]
Ive got two busy days (sending a conference paper to Berlin), I'll take
take a look at this tommorow evening, sorry for the delay!

**Comment by ChristianSch** [comment]
No problem. Good luck with the paper then ;)

**Comment by niedakh** [comment]
thank you Christian! merged it.

**Comment by niedakh** [comment]
I will convert your notebook to a unittest tommorow and add it to all the classifiers we have.

**Comment by ChristianSch** [comment]
Awesome, thank you.

**Pull request merged**
