### PR TITLE
Fixed mlknn predict_proba

### PR DESCRIPTION
**Pull request by resendevinicius**

### CODE REVIEW

**Comment by resendevinicius** [comment]
Please, consider only the last commit

**Comment by aamin21** [comment]
@resendevinicius What issue was the bug causing? Is there an explanation for the bug?

**Comment by resendevinicius** [comment]
> @resendevinicius What issue was the bug causing? Is there an explanation for the bug?

I work with multi-label learning and I kind use traditional algorithms to combine with a technique I'm developing (in which I combine probabilities and use predict_proba to take the probability of traditional algorithms). I noticed that the results were very unsatisfactory when using mlknn in the combination, so I decided to check the probabilities generated by it. If running mlknn's predict_proba for any data set is easy to see that the values are wrong (all values are incredibly low), then I went to the code and realized that the probabilities were not calculated correctly for this algorithm.
The predict function is correct but predict_proba isn't.

**Comment by aamin21** [comment]
> The predict function is correct but predict_proba isn't.

Thank you for your answer. I am trying to use the predict_proba() of MLKNN as well, and was very surprised to see the result myself. As you said, the values were really low. I really need a fix as well. Hopefully @niedakh  can spend some time looking at this PR. 

P.S @resendevinicius  the build failed due to AppVeyor. There is another PR with the fix for that as well.

**Pull request merged**
