### PR TITLE
Replaced 2 tab indentations with 4 spaces each.

### PR DESCRIPTION
**Pull request by xuf12**

### CODE REVIEW

**Comment by ljvmiranda921** [comment]
No merge yet? 😄

**Comment by arthur-gouveia** [comment]
Found the same problem here. Why not merged yet?

**Comment by ChristianSch** [comment]
The issue has been resolved in ljvmiranda921/master I think, which has already been merged into master. I think I even tested it a few days ago. We didn't do a release yet.

@ljvmiranda921 Can you confirm that we can close this pull request?

**Comment by ljvmiranda921** [comment]
Hi, yes this has been resolved already in the previous merge. Although the changes aren't released yet.
You can install the bleeding-edge version here in github via `git clone` then run `python setup.py`. 
👍

**Pull request closed without merging**
